#!/usr/bin/env bash
set -e
pushd . > /dev/null
cd ~/ros_ws/src
if test -d me416_msgs
then
    rm -rf me416_msgs
fi
git clone https://bitbucket.org/tronroberto/ros2me416_msgs.git me416_msgs
popd > /dev/null
