#!/usr/bin/env bash

# Get IP address of all interfaces
ipaddr=$(hostname -I)

# Publish to dweet.io using hostname and ipaddr as message
now=$(date  +"%D %T")
wget --post-data="IP=${ipaddr} @ ${now}" "http://dweet.io/dweet/for/$HOSTNAME" -O /dev/null
