#!/usr/bin/env bash
set -e
sudo apt install -y build-essential bc flex bison

cwd=`pwd`

echo "Adding support for rtl8812au"
git clone https://github.com/aircrack-ng/rtl8812au.git
cd rtl8812au
ARCH=arm64 make -j`nproc`
sudo ARCH=arm64 make install
sudo modprobe 88XXau
cd "${cwd}"

echo "Adding support for rtl8188eu"
git clone https://github.com/ivanovborislav/rtl8188eu.git
cd rtl8188eu
# Configure for ARM64 architecture
sed --in-place 's/RPI_ARM64 = n/RPI_ARM64 = y/' Makefile
sed --in-place 's/I386_PC = y/I386_PC = n/' Makefile
make -j`nproc`
sudo make install
cd "${cwd}"
